name: Codacy Analysis

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  pull_request:

jobs:
  codacy:
    runs-on: ubuntu-latest
    steps:
      - name: Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v4.4.5
